
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"      
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/conf.d:/etc/nginx/conf.d
      - ./web/certs:/etc/nginx/certs
      - ./html:/var/www/html
      - ./web/log/nginx:/var/log/nginx
