
services:
  php:
    image: php:fpm-alpine
    container_name: php
    restart: always
    volumes:
      - ./html:/var/www/html

  php74:
    image: php:7.4-fpm-alpine
    container_name: php74
    restart: always
    volumes:
      - ./html:/var/www/html
