version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"      
    volumes:
      - /home/docker/web/nginx.conf:/etc/nginx/nginx.conf
      - /home/docker/web/conf.d:/etc/nginx/conf.d
      - /home/docker/web/certs:/etc/nginx/certs
      - /home/docker/html:/var/www/html
      - /home/docker/web/log/nginx:/var/log/nginx
