
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqlwebroot
      MYSQL_USER: mysqluse
      MYSQL_PASSWORD: mysqlpasswd
